# Generated by Django 5.2.7 on 2025-10-06 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='reports.report'),
        ),
        migrations.AddField(
            model_name='report',
            name='is_duplicate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='ml_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='ml_predicted_category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='report',
            name='ml_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='ml_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='report',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='report',
            name='similarity_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
