# Generated by Django 5.2.7 on 2025-10-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_add_ml_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='duplicate_of',
        ),
        migrations.RemoveField(
            model_name='report',
            name='is_duplicate',
        ),
        migrations.RemoveField(
            model_name='report',
            name='ml_confidence',
        ),
        migrations.RemoveField(
            model_name='report',
            name='ml_predicted_category',
        ),
        migrations.RemoveField(
            model_name='report',
            name='ml_processed',
        ),
        migrations.RemoveField(
            model_name='report',
            name='ml_processed_at',
        ),
        migrations.RemoveField(
            model_name='report',
            name='similarity_score',
        ),
        migrations.AlterField(
            model_name='report',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Low', max_length=10),
        ),
        migrations.AlterField(
            model_name='report',
            name='risk_level',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Low', max_length=10),
        ),
    ]
