# Generated by Django 5.2.7 on 2025-10-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_remove_report_duplicate_of_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='ml_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='ml_predicted_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='ml_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='ml_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
